version: "3.8"
services:
  point_of_sale_api:
    image: elleined/point-of-sale-api:latest
    container_name: point_of_sale_api
    ports:
      - "8065:8065"
    env_file:
      - .env
    networks:
      - pos_network
    depends_on:
      mysql_server:
        condition: service_healthy
      redis_server:
        condition: service_healthy

  redis_server:
    image: 'redis:latest'
    container_name: redis_server
    ports:
      - '6379:6379'
    networks:
      - pos_network

  mysql_server:
    image: mysql:8.0.32
    container_name: mysql_server
    env_file:
      - mysql.env
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 300s
    networks:
      - pos_network

networks:
  pos_network:
    name: pos_network
    ipam:
      driver: default
    external: false
